### PR TITLE
Added min allowed SquareSize

### PR DESCRIPTION
**Pull request by saching13**
Set min allowed square size for calibration to be greater than 2.2 cm.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Is it the case that below 2.2cm that the calibration is not sufficiently accurate?

**Comment by saching13** [comment]
> Is it the case that below 2.2cm that the calibration is not sufficiently accurate?

It looked like it. User in Discord had good depth image but values were off. Calibrating by increasing square size from 1.8cm to 2.4+ approx fixed issue for him.

**Comment by Luxonis-Brandon** [comment]
Got it, thanks.  We should add that to the calibration documentation as well then @saching13 so that folks know the `why`.

And thanks for the catch/debug with the Discord user!

**Review by VanDavv — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
