### PR TITLE
Oak sync

### PR DESCRIPTION
**Pull request by Erol444**
Logs from `sync_multiple_outputs.py`:
```
{'1_bitstream': <depthai.ImgFrame object at 0x000001766C3F91F0>, '2_passthrough': <depthai.ImgFrame object at 0x000001766C40C2F0>, '2_out': <depthai.ImgDetections object at 0x000001766C40C070>}

{'1_bitstream': <depthai.ImgFrame object at 0x000001766C40BFB0>, '2_passthrough': <depthai.ImgFrame object at 0x000001766C40C070>, '2_out': <depthai.ImgDetections object at 0x000001766C40C2F0>}

{'1_bitstream': <depthai.ImgFrame object at 0x000001766C3F91F0>, '2_out': <depthai.ImgDetections object at 0x000001766C40C2F0>, '2_passthrough': <depthai.ImgFrame object at 0x000001766C40C070>}
```

### CODE REVIEW

**Comment by peskaf** [comment]
Does not work in this example:
```python
from typing import Dict

from depthai_sdk import OakCamera

with OakCamera() as oak:
    color = oak.create_camera('color', encode='h264')
    nn = oak.create_nn('mobilenet-ssd', color)
    nn2 = oak.create_nn('mobilenet-ssd', color)

    def cb(msgs: Dict):
        print(msgs)

    # OK
    #oak.sync([color.out.encoded, nn.out.main], cb)

    # NOT OK
    oak.sync([color.out.encoded, nn.out.main, nn2.out.main], cb)

    oak.start(blocking=True)
```

**Comment by peskaf** [comment]
I also think that is should pass `packets` to the callback, not messages (as `oak.callback(component, cb)` would pass packet to the callback).

**Comment by Erol444** [comment]
@peskaf script below did work for me. wrt Packet - challenge here is that each stream outputs a packet, one approach would be to send an array of packets to the callback. Thoughts?
```
from typing import Dict
from depthai_sdk import OakCamera

with OakCamera() as oak:
    color = oak.create_camera('color', encode='h264')
    nn = oak.create_nn('mobilenet-ssd', color)
    nn2 = oak.create_nn('face-detection-retail-0004', color)
    def cb(msgs: Dict):
        print(msgs)

    oak.sync([color.out.encoded, nn.out.passthrough, nn2.out.passthrough], cb)

    oak.start(blocking=True)
```

**Comment by peskaf** [comment]
This one worked for me as well, it changed when I tried to use `main` output instead of `passthrough`.

Packets: Yes, that is what I thought of (and where something like ID from which component packet is would be useful).

**Comment by Erol444** [comment]
@peskaf Fixed the issue, I apologize for the delay. Now packets' name equals to all stream names combined, so your script above works as expected.

**Review by peskaf — COMMENTED** [review]
Nice, thanks!

**Pull request merged**
