### PR TITLE
Add manual testing script

### PR DESCRIPTION
**Pull request by VanDavv**
This PR introduces a new script for testing - `tests/guided_manual_test.py`. This is a simple OpenCV script that serves as a helper tool when testing the DepthAI device and/or demo script.

The first screen allows selecting desired test areas

image

Then, one by one, the demo script is being run and one has to mark whether the test succeeded or not.
image

After all of the tests from the selected category are run successfully, a success message appears and the user is being redirected back to the menu
image

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
So I just ran it and I ran into a couple issues:

```
Python3 tests/guided_manual_test.py 
Starting manual test procedure. Press the [ESC] key to abort.
AUsing depthai module from:  /Users/leeroy/Library/Python/3.8/lib/python/site-packages/depthai.cpython-38-darwin.so
Depthai version installed:  2.8.0.0
Available devices:
[0] 14442C1061185FD700 [X_LINK_UNBOOTED]
[1] 192.168.1.141 [X_LINK_BOOTLOADER]
Which DepthAI Device you want to use: 0
Traceback (most recent call last):
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 280, in getDeviceInfo
    return device_infos[int(val)]
ValueError: invalid literal for int() with base 10: 'A0'
```
So I think this is because I did a capital `A` (as the screen shows) but actually a lower-case `a` is what is needed?

And then IIRC I did a lower-case `a` and got trapped here:
https://photos.app.goo.gl/dQPUogQwhNPWD1b3A

For this run:
```
Python3 tests/guided_manual_test.py
Starting manual test procedure. Press the [ESC] key to abort.
Using depthai module from:  /Users/leeroy/Library/Python/3.8/lib/python/site-packages/depthai.cpython-38-darwin.so
Depthai version installed:  2.8.0.0
Available devices:
[0] 14442C1061185FD700 [X_LINK_UNBOOTED]
[1] 192.168.1.141 [X_LINK_BOOTLOADER]
[2] 192.168.1.141 [X_LINK_BOOTLOADER]
Which DepthAI Device you want to use: 0
=== TOTAL FPS ===
[depth_raw]: 21.4
[depth]: 21.4
[color]: 22.7
[nn]: 17.7
zsh: terminated  Python3 tests/guided_manual_test.py
```

I ended up having to ctrl-C it.  

And when running the test from directly in the test folder, I saw this:
```
tests % python3 guided_manual_test.py 
Starting manual test procedure. Press the [ESC] key to abort.
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/leeroy/depthai/tests/depthai_demo.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "guided_manual_test.py", line 371, in <module>
    test_cameras()
  File "guided_manual_test.py", line 56, in test_cameras
    subprocess.check_call([*demo_call])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Developer/CommandLineTools/usr/bin/python3', '/Users/leeroy/depthai/tests/depthai_demo.py']' returned non-zero exit status 2.
```

So in general on stuff like this, it should pass the `drunken monkey test`.  Meaning that if a drunken monkey ran into your office, jumped your keyboard and started banging on it, unplugging stuff (like the OAK-D), replugging stuff, etc. it shouldn't crash - it should just provide feedback that the input is invalid, the device is disconnected, etc.

Thoughts?

**Comment by VanDavv** [comment]
Agreed @Luxonis-Brandon, fixed for those two cases and will check for more (like disconnects etc). I think this also goes beyond this PR as we should do the `drunken monkey test` also for the demo script itself

**Comment by Luxonis-Brandon** [comment]
Yes agreed WRT the `drunken monkey test` on the demo script itself.

**Review by Erol444 — APPROVED** [review]
Manual testing works for me, thanks:)

**Pull request merged**
