### PR TITLE
Multi output tensor

### PR DESCRIPTION
**Pull request by szabi-luxonis**
1. Added multi output network support
example: example_run_age_gender_recognition_retail.py
2. Restructured resources/nn, added command line option -cnn,--cnn_model 
Example: 
python3 test.py -cnn person-detection-retail-0013
python3 test.py -cnn mobilenet-ssd
3. Added support to disable depth calculation on bounding box from network:
-dd,--disable_depth
4. Added command line option to specify stream list:
-s, --streams
Example:
python3 test.py --streams metaout previewout left right depth_sipp
python3 test.py -s metaout previewout

### CODE REVIEW

**Comment by Luxonis-Brian** [comment]
Was just testing out some of these CLI options, and they work really well! These flags make it SO much nicer to work with. The examples @szabi-luxonis posted above all work, but I didn't thoroughly test the CNNs or multi-network stuff, as I'm not that familiar with it. 

One thing I noticed was that even after setting `python3 test.py -b 7.5 r 3.5 -e` to store the OBC board config to eeprom, the print statements on the next run (`python3 test.py`) suggested the board settings didn't take:

> depthai: Calibration file is not specified, will use default setting;
> config_h2d json:
> {"_board":{"_homography_right_to_left":[0.988068163394928,0.0029474012553691864,5.067617416381836,-0.008765067905187607,0.9921473264694214,-8.795275688171387,-8.449587767245248e-06,-3.603489403758431e-06,1.0]},"_load_inBlob":true,"_pipeline":{"_streams":[{"name":"metaout"},{"name":"previewout"},{"name":"meta_d2h"}]},"ai":{"calc_dist_to_bb":true},"board":{"clear-eeprom":false,"left_fov_deg":71.86000061035156,"**left_to_rgb_distance_m":0.019999999552965164,"left_to_right_distance_m":0.09000000357627869**,"override-eeprom":false,"store-to-eeprom":false,"swap-left-and-right-cameras":true},"depth":{"padding_factor":0.30000001192092896}}

Not sure if this is a printing issue or an actual read/write to EEPROM issue. The homography seems to be getting loaded from EEPROM, though, as I don't have a depthai.calib file in my /resources/ directory right now.

**Comment by szabi-luxonis** [comment]
Added:
python3 test.py -cnn facial-landmarks-35-adas-0002
python3 test.py -cnn landmarks-regression-retail-0009
python3 test.py -cnn age-gender-recognition-retail-0013
python3 test.py -cnn emotions-recognition-retail-0003

**Comment by Luxonis-Brandon** [comment]
Sweet thanks!

**Comment by Luxonis-Brandon** [comment]
All seems to work well for me.  Tested on microAI (BW1093).

So I do have a question though:
Is there a confidence output from these models?  As it tries to annotate landmarks even when there is no face...  Or is it the case that these models assume there was a successful face-detection (with a confidence thresholding on that detection) prior to this model being run, so there's no reason to have a secondary confidence?

image

And all models work fine for me.  This version is so much nicer for running various models etc.!

Can't wait to get the multi-stage pipeline builder going so that the face detector is used before these models in a configurable fashion.

LGTM, I think good to merge.

Thoughts @alex-luxonis ?

**Comment by szabi-luxonis** [comment]
@Luxonis-Brandon for landmarks recognition there is no confidence, so it assumes that the input is already a face
for age-gender and emotion recognition i added a confidence threshold check, 0.8 (age-gender) and 0.7 (emotion recognition)

**Comment by Luxonis-Brandon** [comment]
Thanks and makes sense. 

With the pipeline builder we’ll be able to have the face detection up front which will be great!

**Comment by Luxonis-Brandon** [comment]
And I’ll test the updates soon and circle back.  Overall this is looking great to me and would love to get merged to master soon as it makes ll the networks so Blum has easier to use.  And then I’ll update the tutorial on how to use DepthAI shortly after that.  

Thought @alex-luxonis?

**Pull request merged**
