### PR TITLE
JPEG and H264 feature

### PR DESCRIPTION
**Pull request by themarpe**
Implemented functionality to capture still JPEG images and a new stream 'video' which outputs h264 encoded color video

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Really excited for this feature!  

So does this pull the latest support for Mac on the build scripts @themarpe ?

When I go to build it on my Mac I get this:
```

DESKTOP-OGSI4CI:depthai-python-extras leeroy$ git reset --hard origin
HEAD is now at 0494691 Merge branch 'frame_metadata'
DESKTOP-OGSI4CI:depthai-python-extras leeroy$ git checkoug master
git: 'checkoug' is not a git command. See 'git --help'.

The most similar command is
	checkout
DESKTOP-OGSI4CI:depthai-python-extras leeroy$ git checkout master
M	depthai-api
Already on 'master'
Your branch is up to date with 'origin/master'.
DESKTOP-OGSI4CI:depthai-python-extras leeroy$ git pull
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 20 (delta 9), reused 14 (delta 8), pack-reused 0
Unpacking objects: 100% (20/20), done.
From https://github.com/luxonis/depthai-python-extras
   c865fb5..6a0c5ee  multi-output-tensor -> origin/multi-output-tensor
 * [new branch]      update_r11.6        -> origin/update_r11.6
Fetching submodule depthai-api
From https://github.com/luxonis/depthai-api
 * [new branch]      update_r11.6 -> origin/update_r11.6
fatal: exec 'rev-list': cd to 'shared/3rdparty/dldt' failed: No such file or directory
Fetching submodule depthai-api/shared/3rdparty/dldt
From https://github.com/opencv/dldt
 + d23f122a...822692f5 master     -> origin/master  (forced update)
Could not access submodule 'ngraph'DESKTOP-OGS
DESKTOP-OGSI4CI:depthai-python-extras leeroy$ git checkout jpeg_h264_feature
M	depthai-api
Switched to branch 'jpeg_h264_feature'
Your branch is up to date with 'origin/jpeg_h264_feature'.
DESKTOP-OGSI4CI:depthai-python-extras leeroy$ git submodule update --init
DESKTOP-OGSI4CI:depthai-python-extras leeroy$ ./depthai-api/build_py_module.sh
grep: /proc/meminfo: No such file or directory
MemAvailable:  MB
[BUILD depthai-api/host/py_module/build] make -j1
[ 14%] Built target nlohmann_json_schema_validator
[ 17%] Building C object CMakeFiles/depthai.dir/Users/leeroy/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/pc/PlatformData.c.o
In file included from /Users/leeroy/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/pc/PlatformData.c:11:
In file included from /Users/leeroy/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/include/XLinkPlatform.h:12:
In file included from /Users/leeroy/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/include/XLinkPrivateDefines.h:13:
/Users/leeroy/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/include/XLinkStream.h:14:13: fatal error: 'pthread_semaphore.h' file not found
#   include "pthread_semaphore.h"
            ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/depthai.dir/Users/leeroy/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/pc/PlatformData.c.o] Error 1
make[1]: *** [CMakeFiles/depthai.dir/all] Error 2
make: *** [all] Error 2
[BUILD depthai-api/host/py_module/build] cp depthai.cpython-37m-darwin.so ../../../../
```

And this is the error I was seeing on Mac before we updated the build scripts.  

Thoughts? 

Will try it on Ubuntu as well to test out the functionality.

**Comment by Luxonis-Brandon** [comment]
I also tried with `git submodule update --recursive` per [here](https://docs.luxonis.com/api/#re-building-from-source-with-specific-branchesetc) and it still stopped on the same error.  

```
git submodule update --recursive
Submodule path 'depthai-api/shared/3rdparty/dldt': checked out 'fe3f978b98c86eaeed3cbdc280e1ffd0bc50d278'
```

Thoughts @alex-luxonis and @szabi-luxonis ?  I could definitely be doing something wrong in the build...

**Comment by alex-luxonis** [comment]
Looks like the branch is based on some older version of `master`, before the support for macOS was added. I'll merge it with master.

**Comment by Luxonis-Brandon** [comment]
> Looks like the branch is based on some older version of master, before the support for macOS was added. I'll merge it with master.

Ah, thanks @alex-luxonis .  So this probably explains the issue I'm seeing on Ubuntu 18.04 as well, but details below in case not.

So trying on Ubuntu 18.04 I'm seeing this:
```
jenkins@beth:~/depthai-python-extras$ python3 test.py
python3 depthai.py 
No calibration file. Using Calibration Defaults.
Using Arguments= {'config_overwrite': None, 'device_id': '', 'dev_debug': None, 'force_usb2': None, 'video': None}
depthai.__version__ == 0.0.10a
depthai.__dev_version__ == 43b4f41cbea2d2cabc7a2b1ea3cd668a551ed3cc
XLink initialized.
Sending device firmware "cmd_file": /home/jenkins/depthai-python-extras/depthai.cmd
Successfully connected to device.
Loading config file
Attempting to open stream config_d2h
watchdog started 1000
Successfully opened stream config_d2h with ID #0!
Closing stream config_d2h: ...
Closing stream config_d2h: DONE.
WARNING: Version (dev) does not match (unknown & 43b4f41cbea2d2cabc7a2b1ea3cd668a551ed3cc)
Available streams: ['meta_d2h', 'left', 'right', 'disparity', 'depth_sipp', 'metaout', 'previewout', 'jpegout', 'video']
CNN configurations read: /home/jenkins/depthai-python-extras/resources/nn/object_detection_4shave/object_detection.json
depthai: Calibration file is not specified, will use default setting;
config_h2d json:
{"_board":{"_homography_right_to_left":[0.988068163394928,0.0029474012553691864,5.067617416381836,-0.008765067905187607,0.9921473264694214,-8.795275688171387,-8.449587767245248e-06,-3.603489403758431e-06,1.0]},"_load_inBlob":true,"_pipeline":{"_streams":[{"name":"jpegout"},{"name":"metaout"},{"name":"previewout"},{"name":"meta_d2h"}]},"ai":{"calc_dist_to_bb":true},"board":{"left_fov_deg":69.0,"left_to_rgb_distance_m":0.019999999552965164,"left_to_right_distance_m":0.09000000357627869,"swap-left-and-right-cameras":true},"depth":{"padding_factor":0.30000001192092896}}
Attempting to open stream config_h2d
Successfully opened stream config_h2d with ID #1!
Writing 1000 bytes to config_h2d
!!! XLink write successful: config_h2d (1000)
Closing stream config_h2d: ...
Closing stream config_h2d: DONE.
Creating observer stream host_capture: ...
Attempting to open stream host_capture
Successfully opened stream host_capture with ID #0!
Creating observer stream host_capture: DONE.
Read: 14514560
Attempting to open stream inBlob
Successfully opened stream inBlob with ID #3!
Writing 14514560 bytes to inBlob
!!! XLink write successful: inBlob (14514560)
Closing stream inBlob: ...
Closing stream inBlob: DONE.
depthai: done sending Blob file /home/jenkins/depthai-python-extras/resources/nn/object_detection_4shave/mobilenet_ssd.blob
Attempting to open stream outBlob
Successfully opened stream outBlob with ID #1!
Closing stream outBlob: ...
Closing stream outBlob: DONE.
CNN input width: 300
CNN input height: 300
CNN input num channels: 3
Host stream start:meta_d2h
Opening stream for read: meta_d2h
Attempting to open stream meta_d2h
Successfully opened stream meta_d2h with ID #5!
Starting thread for stream: meta_d2h
Started thread for stream: meta_d2h
Host stream start:metaout
Opening stream for read: metaout
Attempting to open stream metaout
Successfully opened stream metaout with ID #6!
Starting thread for stream: metaout
Host stream start:previewout
Opening stream for read: previewout
Attempting to open stream previewout
Started thread for stream: metaout
Successfully opened stream previewout with ID #1!
Starting thread for stream: previewout
Started thread for stream: previewout
Host stream start:jpegout
Opening stream for read: jpegout
Attempting to open stream jpegout
Successfully opened stream jpegout with ID #2!
Starting thread for stream: jpegout
Started thread for stream: jpegout
depthai: INIT OK!
E: [xLink] [    811852] [EventRead00Thr] eventReader:218	eventReader thread stopped (err -4)
E: [xLink] [    811852] [Scheduler00Thr] eventSchedulerRun:576	Dispatcher received NULL event!
E: [global] [    811852] [python3] XLinkReadDataWithTimeOut:1494	Event data is invalid
Device get data failed: 7
E: [global] [    811852] [python3] XLinkReadDataWithTimeOut:1494	Event data is invalid
Device get data failed: 7
E: [global] [    811852] [python3] XLinkReadDataWithTimeOut:1494	Event data is invalid
E: [global] [    811852] [python3] XLinkReadDataWithTimeOut:1494	Event data is invalid
Device get data failed: 7
Device get data failed: 7
E: [global] [    811853] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811853] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811853] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811853] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811854] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811854] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811854] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811854] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811855] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811855] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811855] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811855] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811856] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811856] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811857] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811857] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811857] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811858] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/shared/XLink.c:1468
	 Assertion Failed: link != NULL
Device get data failed: 7
E: [global] [    811858] [python3] XLinkReadDataWithTimeOut:1468	/home/jenkins/depthai-python-extras/depthai-api/s
```

Video:
https://photos.app.goo.gl/1Pz74vUbKZGd2JpTA

Running master on this machine and same hardware works fine.

**Comment by alex-luxonis** [comment]
@Luxonis-Brandon I've merged with master, please try again.
I have tested on Ubuntu18.04 with:
`python3 test.py -v myvideo.h264`
Stop after some time with `q`, and play the recorded video:
`ffplay myvideo.h264`

Also, pressing `c` while running will display a still capture.

**Comment by alex-luxonis** [comment]
Could confirm that by running just `python3 test.py` (without the `-v` option), I'm getting the same issue as in the logs above, both before and after the update with master.

**Comment by Luxonis-Brandon** [comment]
> @Luxonis-Brandon I've merged with master, please try again.
> I have tested on Ubuntu18.04 with:
> python3 test.py -v myvideo.h264
> Stop after some time with q, and play the recorded video:
> ffplay myvideo.h264

> Also, pressing c while running will display a still capture.

Sweet thanks for merging with master.  Will give that a run.

> Could confirm that by running just python3 test.py (without the -v option), I'm getting the same issue as in the logs above, both before and after the update with master.

Note on that @themarpe - I'm guessing something simple and could easily see how would slip through the cracks because testing w/ -v makes the most sense for exercising the feature.  

Thoughts?

Thanks, all!

**Comment by alex-luxonis** [comment]
> Note on that @themarpe - I'm guessing something simple and could easily see how would slip through the cracks because testing w/ -v makes the most sense for exercising the feature.

There's a crash on device, that triggers the watchdog. Will let @themarpe look at it.

Also while merging I've deleted the file `example_run_object_detection.py` modified in https://github.com/luxonis/depthai/pull/79/commits/7a691927, that was deleted from master.
And the RPi lib wasn't rebuilt.

**Comment by Luxonis-Brandon** [comment]
Sounds good, thanks.  I wasn't sure on the `example_run_object_detection.py` and if that should be there on master again.  I was thinking test.py (running depthai.py) is way to go now but wasn't sure.

**Comment by Luxonis-Brandon** [comment]
OK, more notes:
1.  This now does work properly on my Mac.
2.  Right-clicking on the JPEG image after clicking `c` to capture a JPEG results in many `Data queue is full video:` and `Data queue is full metaout:` messages - and pauses the `previewout` display.  

This also seems to cause the h.264 encoder to wig out a little bit, as you can see towards the end of this video (around 38 and 43 seconds, it seems):
https://photos.app.goo.gl/mmu23Bfydhakyk4AA

The captured image did save correctly though (and makes me look a bit like serial killer):
jpegout_screenshot_21 04 2020

**Comment by VanDavv** [comment]
@themarpe I get an error when trying to build a new module

```
$ ./depthai-api/build_py_module.sh 
MemAvailable: 620 MB
[BUILD depthai-api/host/py_module/build] cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- optional:-std=c++17
CMake Error at CMakeLists.txt:27 (include):
  include could not find load file:

    ../../shared/3rdparty/dldt/inference-engine/thirdparty/movidius/XLink/XLink.cmake


-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found suitable version "3.7.3", minimum required is "3") 
CMake Error at CMakeLists.txt:34 (add_subdirectory):
  The source directory

    /home/pi/Desktop/depthai-python-extras/depthai-api/host/py_module/3rdparty/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:46 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/pi/Desktop/depthai-python-extras/depthai-api/host/py_module/build/CMakeFiles/CMakeOutput.log".
[BUILD depthai-api/host/py_module/build] make -j1
make: *** No targets specified and no makefile found.  Stop.
[BUILD depthai-api/host/py_module/build] cp *.so ../../../../
cp: cannot stat '*.so': No such file or directory
```

**Comment by alex-luxonis** [comment]
@VanDavv Please run this script, then retry the build:
https://github.com/luxonis/depthai-api/blob/jpeg_h264_feature/install_dependencies.sh

**Comment by VanDavv** [comment]
Thanks @alex-luxonis , did `sudo apt-get install -y libboost-dev libusb-1.0-0-dev` and it worked

**Comment by VanDavv** [comment]
@themarpe running just `python3 test.py` with no arguments gives an error (and the application falls into infinite loop with the same error on and on)

```
$ python3 test.py 
python3 depthai.py 
Using Custom Calibration File: depthai.calib
Using Arguments= {'config_overwrite': None, 'field_of_view': 71.86, 'baseline': 9.0, 'rgb_baseline': 2.0, 'swap_lr': True, 'store_eeprom': False, 'clear_eeprom': False, 'override_calib': False, 'device_id': '', 'dev_debug': None, 'force_usb2': None, 'video': None}
depthai.__version__ == 0.0.10a
depthai.__dev_version__ == 282a0d51fde98e3466b833e20ddaccea5f5f7cd1
XLink initialized.
Sending device firmware "cmd_file": /home/pi/Desktop/depthai-python-extras/depthai.cmd
Successfully connected to device.
Loading config file
Attempting to open stream config_d2h
watchdog started 1000
Successfully opened stream config_d2h with ID #0!
Closing stream config_d2h: ...
Closing stream config_d2h: DONE.
Available streams: ['meta_d2h', 'left', 'right', 'disparity', 'depth_sipp', 'metaout', 'previewout', 'jpegout', 'video']
CNN configurations read: /home/pi/Desktop/depthai-python-extras/resources/nn/object_detection_4shave/object_detection.json
Read: 36
config_h2d json:
{"_board":{"_homography_right_to_left":[1.0028828382492065,0.004322757478803396,-7.890488624572754,-0.007505621761083603,0.9971235990524292,-7.680304527282715,7.495908448618138e-06,-9.8589007393457e-06,1.0]},"_load_inBlob":true,"_pipeline":{"_streams":[{"name":"jpegout"},{"name":"metaout"},{"name":"previewout"},{"name":"meta_d2h"}]},"ai":{"calc_dist_to_bb":true},"board":{"clear-eeprom":false,"left_fov_deg":71.86000061035156,"left_to_rgb_distance_m":0.019999999552965164,"left_to_right_distance_m":0.09000000357627869,"override-eeprom":false,"store-to-eeprom":false,"swap-left-and-right-cameras":true},"depth":{"padding_factor":0.30000001192092896}}
Attempting to open stream config_h2d
Successfully opened stream config_h2d with ID #1!
Writing 1000 bytes to config_h2d
!!! XLink write successful: config_h2d (1000)
Closing stream config_h2d: ...
Closing stream config_h2d: DONE.
Creating observer stream host_capture: ...
Attempting to open stream host_capture
Successfully opened stream host_capture with ID #0!
Creating observer stream host_capture: DONE.
Read: 14514560
Attempting to open stream inBlob
Successfully opened stream inBlob with ID #1!
Writing 14514560 bytes to inBlob
!!! XLink write successful: inBlob (14514560)
Closing stream inBlob: ...
Closing stream inBlob: DONE.
depthai: done sending Blob file /home/pi/Desktop/depthai-python-extras/resources/nn/object_detection_4shave/mobilenet_ssd.blob
Attempting to open stream outBlob
Successfully opened stream outBlob with ID #2!
Closing stream outBlob: ...
Closing stream outBlob: DONE.
CNN input width: 300
CNN input height: 300
CNN input num channels: 3
Host stream start:meta_d2h
Opening stream for read: meta_d2h
Attempting to open stream meta_d2h
Successfully opened stream meta_d2h with ID #1!
Starting thread for stream: meta_d2h
Started thread for stream: meta_d2h
Host stream start:metaout
Opening stream for read: metaout
Attempting to open stream metaout
Successfully opened stream metaout with ID #2!
Starting thread for stream: metaout
Host stream start:previewout
Opening stream for read: previewout
Attempting to open stream previewout
Started thread for stream: metaout
Successfully opened stream previewout with ID #3!
Starting thread for stream: previewout
Host stream start:jpegout
Opening stream for read: jpegout
Attempting to open stream jpegout
Started thread for stream: previewout
Successfully opened stream jpegout with ID #4!
Starting thread for stream: jpegout
Started thread for stream: jpegout
depthai: INIT OK!
watchdog triggered 
Stopping threads: ...
E: [global] [    552053] [python3] XLinkReadData:165	addEventWithPerf(&event, &opTime) failed with error: 3
Device get data failed: 3
E: [global] [    552053] [python3] XLinkReadData:165	addEventWithPerf(&event, &opTime) failed with error: 3
Device get data failed: 3
E: [global] [    552053] [python3] XLinkReadData:165	addEventWithPerf(&event, &opTime) failed with error: 3
Device get data failed: 3
E: [global] [    552053] [python3] XLinkReadData:165	addEventWithPerf(&event, &opTime) failed with error: 3
Closing stream metaout: ...
Closing stream meta_d2h: ...
Closing stream previewout: ...
Closing stream metaout: DONE.
Thread for metaout finished.
E: [global] [    552058] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

E: [xLink] [    552060] [Scheduler00Thr] sendEvents:1036	Event sending failed
E: [global] [    552062] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

Closing stream meta_d2h: DONE.
Thread for meta_d2h finished.
E: [xLink] [    552071] [Scheduler00Thr] sendEvents:1036	Event sending failed
Closing stream previewout: DONE.
Thread for previewout finished.
E: [global] [    552085] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

E: [xLink] [    552086] [Scheduler00Thr] sendEvents:1036	Event sending failed
Device get data failed: 3
Closing stream jpegout: ...
E: [global] [    552088] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

E: [xLink] [    552088] [Scheduler00Thr] sendEvents:1036	Event sending failed
Closing stream jpegout: DONE.
Thread for jpegout finished.
Stopping threads: DONE.
Closing all observer streams: ...
Closing stream host_capture: ...
E: [global] [    552098] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

E: [xLink] [    552098] [Scheduler00Thr] sendEvents:1036	Event sending failed
Closing stream host_capture: DONE.
Closing all observer streams: DONE.
XLink initialized.
No USB device [03e7:2485], still looking... 0.582s [FOUND]
Sending device firmware "cmd_file": /home/pi/Desktop/depthai-python-extras/depthai.cmd
Segmentation fault
Return code:139
```
Looks familiar to what @Luxonis-Brandon posted but it's not the same, so posting it

**Comment by themarpe** [comment]
Thanks for pointing out. I've rushed a bit, didn't run the tests.
I have found the problem and I'm about to push new commit with the issue fixed.

**Comment by themarpe** [comment]
@Luxonis-Brandon @VanDavv Implemented fixes and rebuilt binaries for both x86 and armv7

**Comment by Luxonis-Brandon** [comment]
Meant to say earlier thanks and that will test today.  

Really looking forward to getting this functionality mainlined into DepthAI; and even more-so when we can do it as part of the pipeline builder. 

So a future variant of DepthAI will even have eMMC, so we can save stills and h.264 directly to the eMMC in those cases even when DepthAI is used in an embedded way with a microcontroller or SPI/I2C/UART or with just DepthAI/uAI and nothing else.

**Comment by Luxonis-Brandon** [comment]
Just tested it.  Works great for me.  Tested on BW1093 on Mac OS X.

**Comment by Luxonis-Brandon** [comment]
Just wanted to check @szabi-luxonis and @alex-luxonis what you're thinking on this one.  Thoughts?

**Comment by szabi-luxonis** [comment]
@themarpe please merge latest master into the code, on all 3 branches

**Pull request merged**
