### PR TITLE
Add model zoo w/ model downloader and compiler; remove all blobs

### PR DESCRIPTION
**Pull request by szabi-luxonis**
Related to : #206 
Forked from openvino model downloader.

Models are defined in `.yml` files, and the IR (openvino representation) files are downloaded on the first run, then compiled using [luxonis.com:8080](http://luxonis.com:8080/).
There is a limitation of model size currently in our cloud compiler therefore Yolo-v3 currently doesn't compile, I talked to @VanDavv and we are going to raise the limit.

This downloader can be further improved, so we move everything to [luxonis.com:8080](http://luxonis.com:8080/) providing only the `.yml` file.
In the `yml` file we can specify the conversion parameters  from tf,caffemodel,pytorch to IR model, so we won't be limited to openvino representation. Useful when switching openvino versions, we don't have to update the IR models (xml + bin).

Update:
-The number of resources allocated for model (shaves, cmx_slices) are decided based on the features enabled (rgb camera resolution, object tracker). The number of NCEs is always 1, since when setting it to 2 the FPS may drop if the model is slower than camera FPS.
-Added auto detect mechanism in model downloader: if openvino 2020.1 is installed (properly, with environment variables set), then compilation will be done locally, which is much faster than in cloud if the internet is slow. Added CLI options `mct/--model-compilation-target=[auto, local, cloud]`, by default `auto`

### CODE REVIEW

**Review by Luxonis-Brandon — COMMENTED** [review]
I think that `yaml` may be missing from `requirements.txt` as I ran into this:

```
Leeroys-MacBook-Pro:depthai leeroy$ ./depthai_demo.py
Using depthai module from:  /usr/local/lib/python3.7/site-packages/depthai.cpython-37m-darwin.so
Depthai version installed:  0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
Depthai version required:   0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
No calibration file. Using Calibration Defaults.
Compiling model for 7 shaves, 7 cmx_slices and 1 NN_engines 
Traceback (most recent call last):
  File "/Users/leeroy/depthai/model_compiler/downloader/downloader.py", line 32, in <module>
    import common
  File "/Users/leeroy/depthai/model_compiler/downloader/common.py", line 27, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "./depthai_demo.py", line 379, in <module>
    dai.startLoop()
  File "./depthai_demo.py", line 59, in startLoop
    configMan = DepthConfigManager(args)
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 24, in __init__
    self.generateJsonConfig()
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 143, in generateJsonConfig
    blobMan = BlobManager(self.args, self.compile_model, self.calc_dist_to_bb)
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 328, in __init__
    self.blob_file = self.compileBlob(self.args['cnn_model'])
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 383, in compileBlob
    ret = download_model(nn_model, shave_nr_opt, cmx_slices_opt, NCE_nr, outblob_file)
  File "/Users/leeroy/depthai/depthai_helpers/model_downloader.py", line 19, in download_model
    raise RuntimeError("Model downloader failed! Not connected to the internet?")
RuntimeError: Model downloader failed! Not connected to the internet?
```

**Comment by Luxonis-Brandon** [comment]
The Python package (at least on Mac) for yaml is `pyyaml`.  `python3 -m pip install pyyaml` made it run.

**Comment by szabi-luxonis** [comment]
Indeed, it was automatically installed w/ openvino and I missed to add it to requirements. Fixed.
I didn't test it on mac. (I should get back my laptop from service next week.)

**Comment by Luxonis-Brandon** [comment]
For some reason on my Macbook Pro (details below) I am seeing this error quite often, using BW1093 and BW1092:
```
Leeroys-MacBook-Pro:depthai leeroy$ ./depthai_demo.py
Using depthai module from:  /usr/local/lib/python3.7/site-packages/depthai.cpython-37m-darwin.so
Depthai version installed:  0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
Depthai version required:   0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
No calibration file. Using Calibration Defaults.
Compiled mode found: compiled for 7 shaves, 7 cmx_slices and 1 NN_engines 
XLink initialized.
No USB device [03e7:2485], still looking... 0.938s [FOUND]
Sending internal device firmware
Failed to boot the device: 1-ma2480, err code 3
depthai: Error initializing xlink
['metaout', 'previewout']
Available streams: []
device is not initialized
Pipeline is not created.
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: Invalid argument
Abort trap: 6
```

image

I confirmed that this does not occur when `./depthai_demo.py -fusb2` is used.  So it seems to be a USB3 issue.  I'm going to try develop and main to see if they have the same behavior.

**Comment by Luxonis-Brandon** [comment]
> Indeed, it was automatically installed w/ openvino and I missed to add it to requirements. Fixed.
> I didn't test it on mac. (I should get back my laptop from service next week.)

Great - thanks!

**Comment by Luxonis-Brandon** [comment]
I just confirmed the same USB3 issue occurs on `develop` on this Mac on both BW1093 and BW1092.  Checking `main` now as well.  I think this issue is unrelated to this PR (and may just be the combination of USB cable + Mac USB3 ports).

**Comment by Luxonis-Brandon** [comment]
Yes, same behavior on `main`.  So disregard the USB3 issue I'm seeing.  I've pretty thoroughly abused this USB3 and the ports on this older Mac.  So will investigate with alternate cables/host later.

**Comment by szabi-luxonis** [comment]
For reference. it was mentioned [here](https://luxonis.slack.com/archives/CG1PHMY6M/p1602760565257700) today. And I also encountered issue w/ 1092, even through type-a.

**Comment by Luxonis-Brandon** [comment]
> For reference. it was mentioned [here](https://luxonis.slack.com/archives/CG1PHMY6M/p1602760565257700) today. And I also encountered issue w/ 1092, even through type-A.

Agreed.  1092 shouldn't work on USB3 at all.  The 1093 should though... not sure what's going on there.

**Comment by szabi-luxonis** [comment]
> > For reference. it was mentioned [here](https://luxonis.slack.com/archives/CG1PHMY6M/p1602760565257700) today. And I also encountered issue w/ 1092, even through type-A.
> 
> Agreed. 1092 shouldn't work on USB3 at all. The 1093 should though... not sure what's going on there.

You may try a different orientation of the tpye-c cable. Is there something else connected to the other USB ports?

**Review by Luxonis-Brandon — COMMENTED** [review]
This looks great to me.  I tried a bunch of different models with a variety of NCE/CMX/SH options and they all worked great!  Some examples below:

`./depthai_demo.py -nce 2 -cmx 14 -sh 14 -fusb2 -cnn deeplabv3p_person`
image


The only issue I ran into was will full yolo3:

```
./depthai_demo.py -nce 2 -cmx 14 -sh 14 -fusb2 -cnn yolo-v3
Using depthai module from:  /usr/local/lib/python3.7/site-packages/depthai.cpython-37m-darwin.so
Depthai version installed:  0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
Depthai version required:   0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
No calibration file. Using Calibration Defaults.
Compiling model for 14 shaves, 14 cmx_slices and 2 NN_engines 
################|| Downloading models ||################

========== Downloading /Users/leeroy/depthai/model_compiler/downloads/yolo-v3/FP16/yolo-v3.xml
... 100%, 228 KB, 3430 KB/s, 0 seconds passed

========== Downloading /Users/leeroy/depthai/model_compiler/downloads/yolo-v3/FP16/yolo-v3.bin
... 100%, 120943 KB, 3020 KB/s, 40 seconds passed

################|| Post-processing ||################

Connection timed out!
Traceback (most recent call last):
  File "./depthai_demo.py", line 379, in <module>
    dai.startLoop()
  File "./depthai_demo.py", line 59, in startLoop
    configMan = DepthConfigManager(args)
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 24, in __init__
    self.generateJsonConfig()
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 143, in generateJsonConfig
    blobMan = BlobManager(self.args, self.compile_model, self.calc_dist_to_bb)
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 328, in __init__
    self.blob_file = self.compileBlob(self.args['cnn_model'])
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 383, in compileBlob
    ret = download_model(nn_model, shave_nr_opt, cmx_slices_opt, NCE_nr, outblob_file)
  File "/Users/leeroy/depthai/depthai_helpers/model_downloader.py", line 40, in download_model
    raise RuntimeError("Model compiler failed! Not connected to the internet?")
RuntimeError: Model compiler failed! Not connected to the internet?
```

**Comment by Luxonis-Brandon** [comment]
> You may try a different orientation of the tpye-c cable. Is there something else connected to the other USB ports?

Nothing currently.  Will try other orientations.

And on the full yolov3 issue above, it does occur even after the model is downloaded:
```
./depthai_demo.py -nce 2 -cmx 14 -sh 14 -fusb2 -cnn yolo-v3
Using depthai module from:  /usr/local/lib/python3.7/site-packages/depthai.cpython-37m-darwin.so
Depthai version installed:  0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
Depthai version required:   0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac
No calibration file. Using Calibration Defaults.
Compiling model for 14 shaves, 14 cmx_slices and 2 NN_engines 
################|| Downloading models ||################

========== Retrieving /Users/leeroy/depthai/model_compiler/downloads/yolo-v3/FP16/yolo-v3.xml from the cache

========== Retrieving /Users/leeroy/depthai/model_compiler/downloads/yolo-v3/FP16/yolo-v3.bin from the cache

################|| Post-processing ||################

Connection timed out!
Traceback (most recent call last):
  File "./depthai_demo.py", line 379, in <module>
    dai.startLoop()
  File "./depthai_demo.py", line 59, in startLoop
    configMan = DepthConfigManager(args)
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 24, in __init__
    self.generateJsonConfig()
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 143, in generateJsonConfig
    blobMan = BlobManager(self.args, self.compile_model, self.calc_dist_to_bb)
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 328, in __init__
    self.blob_file = self.compileBlob(self.args['cnn_model'])
  File "/Users/leeroy/depthai/depthai_helpers/config_manager.py", line 383, in compileBlob
    ret = download_model(nn_model, shave_nr_opt, cmx_slices_opt, NCE_nr, outblob_file)
  File "/Users/leeroy/depthai/depthai_helpers/model_downloader.py", line 40, in download_model
    raise RuntimeError("Model compiler failed! Not connected to the internet?")
RuntimeError: Model compiler failed! Not connected to the internet?
```

**Comment by szabi-luxonis** [comment]
> 
> The only issue I ran into was will full yolo3:
> 

Yes. It's mentioned in the PR description that our current online model compiler at [luxonis.com:8080](luxonis.com:8080) has a limitation of maximum model size, we are going to increase it.

**Comment by Luxonis-Brandon** [comment]
> > The only issue I ran into was will full yolo3:
> 
> Yes. It's mentioned in the PR description that our current online model compiler at luxonis.com:8080 has a limitation of maximum model size, we are going to increase it. Full yolo is 120 Mb ..

Oh, my bad.  Sorry I got too excited about trying it out and didn't read!  Sorry about that.  Yes, so this PR looks great to me!

Thanks @szabi-luxonis !

**Review by Luxonis-Brandon — APPROVED** [review]
Looks great to me!

**Comment by szabi-luxonis** [comment]
Online model compiler has been fixed for large networks. (yolo-v3) @Luxonis-Brandon

**Comment by Luxonis-Brandon** [comment]
Thanks!  Will test soon.

**Comment by szabi-luxonis** [comment]
FWIW `tiny-yolo-v3` now runs at 30 fps on the latest branch (14shaves/2nces).
@Luxonis-Brandon 
Screenshot from 2020-10-16 18-32-17

**Comment by Luxonis-Brandon** [comment]
Oh yes that's awesome.  In fact everything seemed faster - even Deeplab.  I got 23fps on deeplabv3 1-class above.  And I think it was lower framerate than that before (CC: @rt-luxonis to confirm, but I think it was 15fps previously).

**Comment by Luxonis-Brandon** [comment]
I did confirm that even on a super slow internet connection this does (eventually) work for full yolov3 (tested on BW1093):

image

**Review by VanDavv — APPROVED** [review]

**Comment by VanDavv** [comment]
Tested with
```
./depthai_demo.py
```
and
```
./depthai_demo.py -cnn face-detection-retail-0004 -cnn2 landmarks-regression-retail-0009
```
and
```
./depthai_demo.py -cnn face-detection-retail-0004 -cnn2 landmarks-regression-retail-0009 -nce 2 -cmx 14 -sh 14
```
and they all worked great, LGTM

**Review by alex-luxonis — COMMENTED** [review]
LGTM.

Currently, a shallow clone of this branch has 4.8MB (compressed, `git clone --depth 1 https://github.com/luxonis/depthai.git -b model_downloader`), and this could possibly be greatly reduced if the NN models description would not be included here (that is only for the users to read about). 
For example the .png in https://github.com/luxonis/depthai/tree/2a0270d/resources/nn/vehicle-detection-adas-0002/description has almost 1MB. Would it be possible to not include the html here on the repo, and instead redirect to this (not sure if best link)? https://docs.openvinotoolkit.org/2019_R1/_vehicle_detection_adas_0002_description_vehicle_detection_adas_0002.html

**Comment by szabi-luxonis** [comment]
After cleanup the compressed branch size is 110KB.

**Comment by Luxonis-Brandon** [comment]
That's sweet!

**Comment by szabi-luxonis** [comment]
Update:
-The number of resources allocated for model (shaves, cmx_slices) are decided based on the features enabled (rgb camera resolution, object tracker). The number of NCEs is always 1, since when setting it to 2 the FPS may drop if the model is slower than camera FPS.
-Added auto detect mechanism in model downloader: if openvino 2020.1 is installed (properly, with environment variables set), then compilation will be done locally, which is much faster than in cloud if the internet is slow. Added CLU options `mct/--model-compilation-target=[auto, local, cloud]`, by default `auto`

**Comment by Luxonis-Brandon** [comment]
Just tried a bunch of models and all of them worked well on the first try, including multi-stage:
image

**Pull request merged**
