### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by VanDavv**
This PR introduces new tests, derived from the previous ones that existed in our repo.

They all work now, code is consistent and uses the same mechanism the previous ones did (DepthAI as a class)

Also made a spacing and imports cleanup in depthai_demo.py.

You can run the tests using the command below
```
python3 run_tests.py
```

and it will run all tests defined in `tests/tests_runner.py` and print out the summary 
image

Streams tests verify if packet from defined stream_name has arrived, CNN tests verify if nnet_packets has arrived

### CODE REVIEW

**Review by szabi-luxonis — APPROVED** [review]
Lgtm

**Comment by szabi-luxonis** [comment]
Change the target branch, first should be merged into develop.

**Comment by VanDavv** [comment]
Cannot test on windows due to https://github.com/luxonis/depthai/issues/263

**Comment by VanDavv** [comment]
Works without issues on Windows 10 with Python 3.9

**Pull request merged**
