### PR TITLE
Add custom wheel for armv6 (pi zero) + aarch64 (jetson)

### LINKED ISSUE #324: Pip wheel for Opencv-python doesn't work on PiZero
Create to separate from similar but unrelated issue for jetson platform from issue #309 

**Describe the bug**
pipi wheel for opencv-python doesn't seem to work on pi zero

**To Reproduce**
1. `python3 -m pip install opencv-python`
2. `python3 -c "import cv2; import numpy as np; blank_image = np.zeros((500,500,3), np.uint8); cv2.imshow('s', blank_image); cv2.waitKey(0)"` 

**Expected behavior**
get black box.

**Screenshots**
//TBA

### PR DESCRIPTION
**Pull request by szabi-luxonis**
The wheel is built on my pi zero, and downloaded from google drive.
Tested on clean Raspberry OS (latest) following the docs (same as any other raspberry)
`sudo curl -fL http://docs.luxonis.com/_static/install_dependencies.sh | bash`
`git clone https://github.com/luxonis/depthai.git`
`python3 install_requirements.py`

`python3 depthai_demo.py -rgbf 5`

Fixes #324

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thank you.  Will test this tomorrow.

**Comment by szabi-luxonis** [comment]
Added wheels for jetson too. (for python3.6, default)
Installation instructions are the same as in docs, opencv, numpy installations are skipped, since they are preinstalle, and installing them will result in `Illegal instruction`
Fixes: #311

**Comment by Luxonis-Brandon** [comment]
Trying this now on Pi Zero.

**Comment by Luxonis-Brandon** [comment]
I forgot how slow the pi zero is.  Trying more now.

**Comment by szabi-luxonis** [comment]
> I forgot how slow the pi zero is. Trying more now.

Yeah. It's one of the slowest host that can run depthai through USB.

**Comment by Luxonis-Brandon** [comment]
image
image
image

Yep, this is good to go.  Thanks @szabi-luxonis !

**Review by Luxonis-Brandon — APPROVED** [review]

**Comment by shirvonp** [comment]
Still no luck on the Jetson nano,I get the below when trying to run install_requirements.py:


_Requirement already satisfied: pip in /home/shirvon/.local/lib/python3.6/site-packages (21.3.1)
WARNING: Skipping opencv-python as it is not installed.
WARNING: Skipping opencv-contrib-python as it is not installed.
WARNING: Skipping depthai as it is not installed.

Usage:   
  /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
  /usr/bin/python3 -m pip install [options] <archive url/path> ...

option --use-deprecated: invalid choice: 'html5lib' (choose from 'legacy-resolver', 'out-of-tree-build')
Traceback (most recent call last):
  File "install_requirements.py", line 47, in <module>
    subprocess.check_call(pip_package_install + ["-r", "requirements.txt"], cwd=scriptDirectory)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-U', '--prefer-binary', '--use-deprecated=html5lib', '--user', '-r', 'requirements.txt']' returned non-zero exit status 2._

**Comment by szabi-luxonis** [comment]
CC: @VanDavv on the above
Jetson uses `python3.6`, for which the latest supported pip is `21.3.1`.
`--use-deprecated` is not available for that pip version.

**Comment by VanDavv** [comment]
thanks @szabi-luxonis, I just updated the main and removed this flag. It's not needed now as the most recent pip versions don't throw an error if html format is incorrect, just warning.

**Pull request merged**
