### PR TITLE
add --report flag

### PR DESCRIPTION
**Pull request by VanDavv**
This flag allows to get DepthAI usage info on the terminal during the runtime.
Example output logs

```
Drr used / total - 75.58 / 414.55 MiB
Cmx used / total - 2.37 / 2.50 MiB
LeonCss heap used / total - 33.33 / 46.35 MiB
LeonMss heap used / total - 5.07 / 27.40 MiB
Chip temperature - average: 35.35, css: 36.06, mss: 34.64, upa0: 35.11, upa1: 35.59
Cpu usage - Leon OS: 27.15%, Leon RT: 1.70 %
----------------------------------------
Drr used / total - 75.58 / 414.55 MiB
Cmx used / total - 2.37 / 2.50 MiB
LeonCss heap used / total - 33.33 / 46.35 MiB
LeonMss heap used / total - 5.37 / 27.40 MiB
Chip temperature - average: 37.77, css: 38.88, mss: 37.24, upa0: 37.94, upa1: 37.01
Cpu usage - Leon OS: 27.33%, Leon RT: 23.24 %
----------------------------------------
Drr used / total - 75.58 / 414.55 MiB
Cmx used / total - 2.37 / 2.50 MiB
LeonCss heap used / total - 33.33 / 46.35 MiB
LeonMss heap used / total - 5.37 / 27.40 MiB
Chip temperature - average: 38.12, css: 39.58, mss: 36.53, upa0: 38.88, upa1: 37.48
Cpu usage - Leon OS: 50.82%, Leon RT: 32.86 %
----------------------------------------
Drr used / total - 75.58 / 414.55 MiB
Cmx used / total - 2.37 / 2.50 MiB
LeonCss heap used / total - 33.33 / 46.35 MiB
LeonMss heap used / total - 5.37 / 27.40 MiB
Chip temperature - average: 38.65, css: 39.11, mss: 38.18, upa0: 38.65, upa1: 38.65
Cpu usage - Leon OS: 56.26%, Leon RT: 38.27 %
----------------------------------------
```

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks.  LGTM.  Will see what Szabi thinks.  

So as a separate effort, we should make a `-metaplot` of something like that that shows a line-plot of all of these over time with a legend.  Not on this PR, but a nice-to-have later.  This will make testing/logging a bit easier.  

Thoughts?

**Comment by szabi-luxonis** [comment]
Printing used memory every time might be too verbose,
Should we print only if it changed compared to previous values? Or make `meta` flag configurable? (Temperature, cpu usage, memory consumption)

**Comment by szabi-luxonis** [comment]
> I updated the meta flag so now it accepts `"temp", "cpu", "memory"`.
> And I think it would make sense to add a `--meta_plot` as @Luxonis-Brandon suggested that would display these on a graph of some sort.
> I took a quick look at a tool that maybe would allow us to reprint the whole meta message, so it would just update its logs instead of adding a new ones, and I found [this thread](https://stackoverflow.com/questions/6840420/rewrite-multiple-lines-in-the-console) that suggested that such solution would not be cross-platform friendly, but also pointed to [this package](https://github.com/Yinzo/reprint) that would allow to implement this solution pretty easily

Should we raneme "meta" to "report"?

You can save the values in .csv file and plot them like [here](https://www.kite.com/python/answers/how-to-plot-data-from-a-csv-file-in-python#:~:text=Use%20nump.,pyplot.)

**Comment by VanDavv** [comment]
@szabi-luxonis I renamed `--meta` to --report` and added `--report_file` - it prevent stdout output and writes reports to a CSV file (example here - [log.csv](https://github.com/luxonis/depthai/files/6451912/log.csv))

I'll add visual representation of this data in next PRs

**Review by szabi-luxonis — APPROVED** [review]

**Pull request merged**
