### PR TITLE
When max_fps is requested, drop frames based on sequence number 

### LINKED ISSUE #98: calibrate.py sometimes does nothing when hitting space bar
On the BW1097 sometimes calibrate.py does nothing at all when hitting space bar.  No green display of it working, no error display, etc.  It just sits there for a while.

We should correct this.  If the system is stuck processing, we should display this so that the user knows what's going on.

### PR DESCRIPTION
**Pull request by szabi-luxonis**
When max_fps is requested, drop frames based on sequence number rather than arrival time.
Fixes #98

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Ah sweet thanks!  

So as you mention this should address the issue we’re seeing with calibrate.py when limiting the framerate.

**Comment by szabi-luxonis** [comment]
Yes, just reverted commit that removed limiting on embedded, it's back to 10 fps for calibrate.py.
Also, max_fps is consistent now, if you request 20 fps, you receive 20.

**Comment by Luxonis-Brandon** [comment]
Oh double-sweet thanks!

**Comment by szabi-luxonis** [comment]
Combining with : https://github.com/luxonis/depthai-api/pull/18/commits/dbb699672a966b29dd45bb582b6918dc25dc6879
on another PR, will also get rid of data queue full messages.

**Pull request merged**
