### PR TITLE
Frame metadata + calibration improvement

### PR DESCRIPTION
**Pull request by Luxonis-Brian**
@themarpe, your changes worked well. I was able to check that two adjacent packets were less than 1ms difference in time stamps. That seemed to be good enough to prevent L/R captures from different frames being used for a calibration pair. I also added a python list "buffer" that acts to pick out the two most recent data packets, rather than working up from the buffered data stream. The data stream doesn't seem to be subscriptable, so I couldn't find an easy way to select the two most recent items. 

I'm sure there's something obvious I didn't try :)

I pushed my stuff up on top of yours since it was easy, but if there's a better way to do this, please let me know and I'll do that. Apologies for not knowing the conventions here.

### CODE REVIEW

**Comment by VanDavv** [comment]
@Luxonis-Brian I left my review on #68 , would be great to have your feedback on it - initialy wanted to do the comments and explain how I would do it, but the same amount of time it took me to actually write it

**Comment by VanDavv** [comment]
Since #68 was merged, this now is LGTM

**Comment by Luxonis-Brian** [comment]
LGTM too. Think this can be merged into master.

**Comment by Luxonis-Brian** [comment]
@themarpe, in testing your latest changes the 1ms timestamp difference we had been using was no longer large enough to reliably capture a frame pair when pressing spacebar. I didn't test to find the threshold but a 10ms difference did work. 

This is on the 1097 compute module.

**Comment by VanDavv** [comment]
@Luxonis-Brian should me merge this?

**Comment by alex-luxonis** [comment]
There is an issue with Left/Right sync as @Luxonis-Brian pointed above. We'll work to resolve this first.

**Comment by themarpe** [comment]
Rebuilt the binaries. If everyone is okay with the changes I'll merge with master.

**Comment by Luxonis-Brandon** [comment]
Testing this now.

**Comment by Luxonis-Brandon** [comment]
So in testing this it seems the -iv and -ih flags do not seem to be honored from https://github.com/luxonis/depthai/pull/71 . I'm guessing this is the conflict with calibrate.py?  Looking now.

**Comment by Luxonis-Brandon** [comment]
OK this looks great to me!  It works properly on the BW1097.  In testing this I discovered calibrate.py crashes on Mac OS X (https://github.com/luxonis/depthai/issues/78) for this version and also Master - so not an issue with this PR.

LGTM.

**Comment by Luxonis-Brian** [comment]
Just checked that the 1ms time stamp flag was working, and it is. I think we're good here. Thanks @themarpe.

**Comment by szabi-luxonis** [comment]
@themarpe please open PR on depthai-api too

**Pull request merged**
