### PR TITLE
Implement config_camera resize for mono cameras

### PR DESCRIPTION
**Pull request by hexbabe**
Addresses: https://github.com/luxonis/depthai/issues/1136

### CODE REVIEW

**Comment by hexbabe** [comment]
@jakaskerl @Erol444 Hey sorry, please re-run workflows and review the code again. Made some more defensive code changes. Thank you!

**Comment by hexbabe** [comment]
Seems like the workflows are failing for credential reasons

**Comment by Erol444** [comment]
Hi @hexbabe ,
We'll be sunsetting the SDK in favour of DepthAI v3. A lot of functionality has already been ported, and it's more customizable. We apologize for the inconvenience.

**Comment by hexbabe** [comment]
> Hi @hexbabe , We'll be sunsetting the SDK in favour of DepthAI v3. A lot of functionality has already been ported, and it's more customizable. We apologize for the inconvenience.

Okay thanks for letting me know

**Pull request closed without merging**
