### PR TITLE
Develop merge - release 0.3.0.0

### PR DESCRIPTION
**Pull request by VanDavv**
Awaiting https://github.com/luxonis/depthai/pull/242

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks.

So if #244 was already present in `main` (is it @Luxonis-Brian ?) I think we should merge before that.  And then we can hot-fix `main` based on the fix for #244 .  Thoughts?

**Comment by Luxonis-Brian** [comment]
checking @Luxonis-Brandon....

**Comment by szabi-luxonis** [comment]
> Thanks.
> 
> So if #244 was already present in `main` (is it @Luxonis-Brian ?) I think we should merge before that. And then we can hot-fix `main` based on the fix for #244 . Thoughts?

@alex-luxonis already fixed it, and opened a PR for it (waiting for CI to finish)

**Comment by Luxonis-Brandon** [comment]
Ok perfect thanks!

**Comment by alex-luxonis** [comment]
Yes, it's good to have #244  fixed, as the issue was not present in main.

**Pull request merged**
