### PR TITLE
updated code to use version 2.9.0.0

### PR DESCRIPTION
**Pull request by franva**
Updated the code to use version 2.9.0.0

### CODE REVIEW

**Comment by VanDavv** [comment]
Wow, that's great, thanks for your contribution @franva! Will give it a try in a minute but looks good at a first glance

**Review by Erol444 — CHANGES_REQUESTED** [review]
Could you update the version of the depthai to 2.9 in `requirements.txt` as well? Thanks!

**Comment by VanDavv** [comment]
@Erol444 I just updated that and it works without issues on my end

**Review by VanDavv — APPROVED** [review]

**Review by Erol444 — APPROVED** [review]
Great thanks!

**Comment by franva** [comment]
wow so efficient guys~! I just walked out to pick up my stuff and back to home saw this all done haha.
Great team work~!

**Comment by franva** [comment]
hi @Erol444 and @VanDavv 

Just a question, since version 2.9.0.0 already included wheels for `opencv-python` and `opencv-contrib-python`, 
should we remove these 2 packages from the `requirements.txt`?

**Comment by Erol444** [comment]
Hello @franva , I don't think the library itself has these dependencies, just the depthai_demo. Could you elaborate, please?
Thanks, Erik

**Pull request merged**
