### PR TITLE
Complete DepthAI-SDK refactor

### PR DESCRIPTION
**Pull request by Erol444**
Started proposing the architecture for the complete SDK refactor. TBD (everything).

Components:

- [x] ColorCamera
- [x] NNcomponent
- [x] StereoComponent
- [x] Syncing
- [x] Visualizer
- [x] Supported NN models (by sdk), json config parsing
- [x] Recording
- [x] Docs & Examples

Nice-to-haves

- [x]  Integrate Geaxgx's [DepthAI Pipeline Graph](https://github.com/geaxgx/depthai_pipeline_graph) tool, eg. `cam.show_graph()`
- [ ] Integrate Roboflow's [roboflowoak](https://pypi.org/project/roboflowoak/) package to run inference on a model downloaded from roboflow platform

### CODE REVIEW

**Comment by Erol444** [comment]
Recording pipeline
recording-pipeline

**Comment by Erol444** [comment]
(2D) Object Detection

**Comment by Erol444** [comment]
Car tracker
car-tracker

**Comment by Erol444** [comment]
car tracking pipeline
image

**Review by themarpe — COMMENTED** [review]
Reasons for pulling in node_graph_qt instead of making it a dependency?

**Comment by Erol444** [comment]
@themarpe It's because that's how the original geax's tool was implemented. In the future we can look into adding it as a dependency

**Review by daniilpastukhov — APPROVED** [review]

**Comment by themarpe** [comment]
Docker build is failing. Although not strictly necessary, it'd be nice to fix

**Comment by Erol444** [comment]
@themarpe  will address in next PR - creating `minimal-requirements.txt`

**Pull request merged**
