### PR TITLE
Installer Windows Signing

### PR DESCRIPTION
**Pull request by themarpe**
Note: To be squash merged

Adds CI to sign the launcher on release.

Also renames the launcher workflow to demo workflow, to be able to add other related steps as well.

@VanDavv TODO - test the release, by pushing a temporary tag and removing it afterwards (also feel free to modify the draft release that gets created by the action)

### CODE REVIEW

**Comment by themarpe** [comment]
@VanDavv 
```
${{ git tag --sort=-creatordate | grep -v sdk | sed -n 2p }}
```
Not sure if `${{ ... }}` syntax executes commands - I think this is GH things only
Maybe assign it to a variable before hand, and then access it using that: https://stackoverflow.com/a/57989070

**Comment by VanDavv** [comment]
@themarpe I have tried
- Github-only syntax `${{ .. }}` - https://github.com/luxonis/depthai/pull/542/commits/2cd9f72492da25fd0b0d7510ec433ca0df3b2697#diff-956b4e4555d79066522d1f121c79e116a7801f349a93fa6c4658d2a64e20292eR77
- Bash syntax `${ .. }` - https://github.com/luxonis/depthai/pull/542/commits/f11794d9ebd5bc9418b27de48ece670493e512dd#diff-956b4e4555d79066522d1f121c79e116a7801f349a93fa6c4658d2a64e20292eR77
- Using $env:GITHUB_ENV - https://github.com/luxonis/depthai/pull/542/commits/cb31cde09ddb33d75fe732559edffc3fb61ac2e4#diff-956b4e4555d79066522d1f121c79e116a7801f349a93fa6c4658d2a64e20292eR64
- Using `set-output` - https://github.com/luxonis/depthai/pull/542/commits/3aedd38651992a186863dc27ba53c519fd9d357c#diff-956b4e4555d79066522d1f121c79e116a7801f349a93fa6c4658d2a64e20292eR65

None of these worked unfortunately

**Review by VanDavv — APPROVED** [review]
But aside from that, LGTM

**Comment by themarpe** [comment]
What is the output of the final `set-output` case?

**Comment by VanDavv** [comment]
@themarpe it was not set  (the Full Changelog URL should end with `/<tag1>..<tag2>`, whereas here it's `/..<tag2>`

Full job - https://github.com/luxonis/depthai/runs/4311759616

Screenshot 2021-11-24 at 16 05 01

**Pull request merged**
