### PR TITLE
depthai_demo UI and visualisation improvements

### PR DESCRIPTION
**Pull request by dhruvsheth-ai**
These are some improvements in UI, without affecting the whole Code structure. 
Reference - https://github.com/luxonis/depthai-python/pull/206

Changelog - Updated fonts, and sizes, placement
                 - Generates Random Colored bounding boxes each time, more in shades of blue.
                 - Added a trackbar to the left to visualise depth in ratio

Example - 
2021-04-21-191649_848x480_scrot

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks for this!

**Comment by VanDavv** [comment]
Thanks @dhruvsheth-ai .
The new look of bounding box and FPS output is very nice, but I'm not convinced about the Ztrackbar - it's big and can potentially collide with other objects in the preview

**Comment by VanDavv** [comment]
Since I updated the gen2 branch with a major refactor, I took the liberty of merging it to your branch @dhruvsheth-ai, so it's up to date with `gen2` head (had merge conflicts before)

**Comment by dhruvsheth-ai** [comment]
> Thanks @dhruvsheth-ai .
> The new look of bounding box and FPS output is very nice, but I'm not convinced about the Ztrackbar - it's big and can potentially collide with other objects in the preview

Thanks for the suggestion @VanDavv and I agree. Apart from the Ztrackbar in persons detected, it collides with other objects. That would only work with output size greater than 540 x 320. Also, I'll try to assign a random color per class ( as per @Erol444 suggestion )

**Comment by dhruvsheth-ai** [comment]
I've removed the Z trackbar and this can be merged now, sorry for the delay. I had been trying to assign a random color for eac class, but it was an  issue when using custom cnn for the demo. I'll update if I find a way to implement it.

**Comment by VanDavv** [comment]
Oh, sorry, I didn't know that this PR will end up closed after we merged #349 , sorry @dhruvsheth-ai. I would like to merge these changes, can you change a base branch to `main` so that I can merge it?

**Comment by dhruvsheth-ai** [comment]
No issues @VanDavv . Since, this had been closed - I opened another PR, with branch as `main`.
https://github.com/luxonis/depthai/pull/364

**Pull request closed without merging**
