### PR TITLE
Migrate demo script to Gen2

### PR DESCRIPTION
**Pull request by VanDavv**
This PR is currently in progress
Gen2_demo script is able to utilize model downloader used in gen1 demo to download and convert the blobs, and there is support for both mobilenet, yolo, and generic neural networks. Users can now run this demo to run an nn of a choice and see the output on the screen.

A couple of todos:

- [x] **Provide spatial coordinates of the detected bounding box**
- [x] replace gen1 downloader with blobconverter cli
- [x] support for `rgbr` parameter
- [x] support for `rgbf` parameter
- [x] support for `-cs` parameter
- [x] support for `-monor` parameter
- [x] support for `-monof` parameter
- [x] support for `-dct` parameter
- [x] support for `-med` parameter
- [x] support for `-lrc` parameter

I'll be working on these in the following days and then mark the PR as ready

### CODE REVIEW

**Comment by Erol444** [comment]
Spatial coordinates PR: https://github.com/luxonis/depthai/pull/350

**Comment by Luxonis-Brandon** [comment]
Cool to see more progress on this.  Excited for this to be available for quickly trying out DepthAI features/functionalities!

**Comment by VanDavv** [comment]
In progress - Gen2 calibration script. `depthai_demo,py` is ready for first review @szabi-luxonis @themarpe, looking forward to your suggestions

**Comment by saching13** [comment]
@VanDavv Flashing calibration to EEPROM is not available on main of gen2. And adding it to main of gen2 here might lead to extra questions from users when they try it.
 So may be we can keep that in different branch till this [PR](https://github.com/luxonis/depthai-core/pull/101) gets merged ?
 and will add write to EEPROM at the end of the same script.
 
 Thoughts ?

**Review by themarpe — CHANGES_REQUESTED** [review]
Blob downloading happens in on first run, but no indication to the user. This seems like the program freezes as no other output is present in the mean time.

Add:
 - Indication of downloading progress or at least that downloading is happening
 - Final blob location (cache, ...) so users can purge if needed

**Comment by VanDavv** [comment]
It looks now like this @themarpe , bumped `blobconverter` package
```
Downloading /home/vandavv/.cache/blobconverter/mobilenet-ssd_openvino_2021.3_13shave.blob...
[==================================================]
Done
```

**Comment by themarpe** [comment]
Default run `python3 depthai_demo.py` doesn't work on OAK-1 devices.
Need to implement a check for device capabilities in `depthai-core` but maybe for now we should issue a warning?

**Comment by szabi-luxonis** [comment]
Let's merge it, since it's functional, to not confuse people w/ gen2 vs gen1. (depthay vs depthai-python)
When we will be able to retrieve device capabilities (OAK1 vs OAK-D) we will update the script, until then print a warning maybe as @themarpe  suggested?
Before merging create a gen1_main, gen1_develop branch based on current main and develop branches keeping the capability of easily switching to gen1.
Thoughts? 
@Erol444 @VanDavv

**Comment by VanDavv** [comment]
@szabi-luxonis I added a param or, if not provided, I ask user to provide a device type
image

I'll merge latest main to gen2 so it's mergeable.
Thoughts on merging @themarpe @Erol444 ?

**Comment by Luxonis-Brandon** [comment]
> Let's merge it, since it's functional, to not confuse people w/ gen2 vs gen1. (depthay vs depthai-python)
> When we will be able to retrieve device capabilities (OAK1 vs OAK-D) we will update the script, until then print a warning maybe as @themarpe suggested?
> Before merging create a gen1_main, gen1_develop branch based on current main and develop branches keeping the capability of easily switching to gen1.
> Thoughts?
> @Erol444 @VanDavv

Just wanted to say, yes, I 100% agree with this.  ^. Thanks, all.

**Comment by themarpe** [comment]
> @szabi-luxonis I added a param or, if not provided, I ask user to provide a device type
> image
> 
> I'll merge latest main to gen2 so it's mergeable.
> Thoughts on merging @themarpe @Erol444 ?

If its okay to work with non-release build I'd go with using the `device_improvements` as provides needed API to not need the above.

**Comment by VanDavv** [comment]
@themarpe the `device_improvements` branch worked well (added support in #362), I think we can go ahead and merge this PR

**Review by szabi-luxonis — CHANGES_REQUESTED** [review]
Cleanup `install_requirements.py` script, it has leftover custom wheels for pi zero and jetson. Now we have jetson (arm64) wheels.

**Review by szabi-luxonis — APPROVED** [review]

**Review by themarpe — APPROVED** [review]

**Pull request merged**
