### PR TITLE
Add keyboard interrupt catch blocks

### PR DESCRIPTION
**Pull request by VanDavv**
This PR adds handles for KeyboardInterrup errors, exiting the program gracefully now

### CODE REVIEW

**Review by themarpe — APPROVED** [review]
LGTM if these are the highest possible levels of handling this exception (eg. wrap the entry which will take care if this exception is raised at any level deeper)

**Comment by themarpe** [comment]
Also make sure that `sys.exit(0)` is the right thing to do. What if we are saving a file? Does GUI exit cleanly? ...

**Comment by VanDavv** [comment]
> is the right thing to do. What if we are saving a file? Does GUI exit cleanly? ...
@themarpe this is all handled by context managers (or at least should be). And actually, system exit is another exception - `SystemExit` - and can even be caught, so I think it will go up through the call stack and exit gracefully, same as the KeyboardInterrupt does, but without traceback and with different exit code.
I'll gave it a try a couple of times and worked as expected, but didn't test it yet with encoding enabled, will test if that behaves as it should

**Comment by themarpe** [comment]
Thanks - if it acts that way then that is great - thought it was more of an "exit" equivalent, which just exits the process ungracefully.

**Pull request merged**
