### PR TITLE
Fix OpenPose nn

### PR DESCRIPTION
**Pull request by VanDavv**
This PR fixes the` openpose2` neural network, it crashed on main with

```
Traceback (most recent call last):
  File "./depthai_demo.py", line 264, in <module>
    nn_data = nn_manager.decode(in_nn)
  File "/Users/leeroy/depthai/depthai_helpers/managers.py", line 469, in decode
    return self.handler.decode(self, in_nn)
  File "/Users/leeroy/depthai/resources/nn/openpose2/handler.py", line 152, in decode
    valid_pairs, invalid_pairs = getValidPairs(outputs, w, h, detected_keypoints)
  File "/Users/leeroy/depthai/resources/nn/openpose2/handler.py", line 46, in getValidPairs
    pafA = outputs[0, mapIdx[k][0], :, :]
IndexError: index 47 is out of bounds for axis 1 with size 46
```

The source of this issue was the `[::-1]` transformation of tensor dimensions. The bug that it resolved was fixed in the latest API release and after the update, the transformation started to bring the opposite effect (yielded incorrect tensor dims)

Also, since we're using full FOV now for preview, had to adjust `handler.py` for openpose to scale the NN results accordingly

### CODE REVIEW

**Comment by VanDavv** [comment]
One note here: since we're using a full FOV preview, the results are being scaled to fit the target frame. This is mostly fine except that networks like deeplab (that return a full frame overlay) tend not to scale well and can be inconsistent around the edges. The best way to visualize them is to use `-s nn_input` as then the NN results will be applied without any scaling

**Review by themarpe — APPROVED** [review]
LGTM - might be good to check any other places for the invalid transformation, mainly depthai-experiments

**Comment by Luxonis-Brandon** [comment]
Yes the handling of the NN data looks wrongly-scaled @VanDavv :

image

So I think we should do a follow-up PR to either fix these directly, or if we can't, make the preview size for such networks be the the same aspect ratio of the neural network.

Thoughts?

**Comment by Luxonis-Brandon** [comment]
We should merge this first though... as this is better than crashing.  But we should then circle back to make sure the overlays are correct - doing whatever is necessary to ensure that.

**Review by Luxonis-Brandon — APPROVED** [review]
I'd say let's merge.  Please circle back to fix the [scaling error](https://github.com/luxonis/depthai/pull/435#issuecomment-891394387) though with a new PR.

**Comment by VanDavv** [comment]
Sure, will work on this and circle back with PR

**Comment by VanDavv** [comment]
@Luxonis-Brandon the PR with fixes is [here](https://github.com/luxonis/depthai/pull/438)

**Comment by Luxonis-Brandon** [comment]
Thanks!

**Pull request merged**
