### PR TITLE
Cleanup source code, add depth_color_h fps limitation

### PR DESCRIPTION
**Pull request by szabi-luxonis**
1. Cleaned up source code in depthai-api
2. Added fps limitation option for depth_color_h stream

### CODE REVIEW

**Comment by szabi-luxonis** [comment]
Add command line option to limit fps per stream.
Usage: -s previewout,15 depth_sipp,15

**Comment by Luxonis-Brandon** [comment]
Thanks!  That will be so nice and clean!

**Comment by Luxonis-Brandon** [comment]
Testing this on Mac, seems to work great.  
Examples tested:
`python3 test.py -s depth_sipp,5 metaout,30 previewout,1`
image

`python3 test.py -s left,1 right,1 depth_sipp,2 metaout,3 previewout,5`
image

Going to test on Raspberry Pi and Ubuntu 18.04 now as well.

**Comment by Luxonis-Brandon** [comment]
OK, running into something interesting now that I'm trying higher framerates.  When I do `python3 test.py -s previewout,30` for example the highest framerate I see is ~22FPS:
image

Running the equivalent command with the old format for requesting a per-stream frame-rate limit results in the same exact behavior:
python3 test.py -co '{"streams": [{"name": "previewout", "max_fps": 30.0}]}'

So that makes me think this is nothing new to this PR (so shouldn't block it's merge).  To double check that this command produces the same limited FPS when the fps is set to 30, below is this same legacy-format FPS limit on `Master`:
```
git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
jenkins@beth:~/depthai$ git pull
Already up to date.
jenkins@beth:~/depthai$ python3 test.py -co '{"streams": [{"name": "previewout", "max_fps": 30.0}]}'
```

image

So yes this is definitely not a new thing (and also, to be clear, it might not be a thing that even matters... as for higher framerates one could just not specify a framerate to get to 30fps).

**Comment by Luxonis-Brandon** [comment]
Also tested this on the Rpi (noted I did not included calibration, so that video looks bad; ignore it).  

Ran with `python3 test.py left,1 right,2 depth_sipp,3 previewout,5` and it worked properly on the BW1097:
image
image

**Comment by Luxonis-Brandon** [comment]
Thoughts on this one @alex-luxonis ?

**Pull request merged**
