### PR TITLE
Sanitize NN output (NaN, Infinite); handle corrupted frames, LRU frame queue replace policy

### PR DESCRIPTION
**Pull request by szabi-luxonis**
Add checks in NN decode to handle floating point exceptions.
Discard corrupted frames.
Implement LRU replace policy for frame queue, replace the oldest frame in the queue in case of overflow.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks!  Chris and Lukasz were just needing this!

**Comment by Luxonis-Brandon** [comment]
Good idea; I like that - I actually hadn’t checked the files changed yet and had assumed (incorrectly) that this was being added to the C++ backend.

**Comment by szabi-luxonis** [comment]
> Would it be possible to move some of these validations in the C++ lib backend?
> In the idea of keeping the python script clean...

TensorEntry validations were moved into library

**Comment by Luxonis-Brandon** [comment]
This works find for me on OS X.

**Comment by Luxonis-Brandon** [comment]
Works fine on BW1097 also.   

Going to let it run over night pointed at its own monitor (so it's constantly detecting at least something).

**Comment by Luxonis-Brandon** [comment]
Mention in slack already but reproducing here for posterity:

Brandon:

> So @szabi-luxonis  with the sanitize PR it successfully prevented the NaN and other errors which would usually cause the watchdog to have to trigger.
> 
> - And ran for at least 6 hours if not a lot more.
> - I think exposed a new one that occurs much less often probably, above ^
> - Manually re-running it after this it runs fine.
> - Note that the watchdog did not catch this one...

Szabi:

> I was able to reproduce this issue artificially on PC, I will push a possible fix in a few minutes.

**Comment by Luxonis-Brandon** [comment]
Thanks for the update/fix for this.  Going to stop the Pi from running and get it doing a 24-hour run again.

And also test this latest on Mac and Ubuntu real quick.

**Comment by Luxonis-Brandon** [comment]
This is now running on the BW1097 (started 33 minutes ago), on Mac (just now) and Ubuntu (also just now).  

Will let them all run for a long time and circle back.

**Comment by Luxonis-Brandon** [comment]
So I can confirm @szabi-luxonis that the error that occurred last time which caused the host code to stop/exit (the `too many indices for array` issue) did occur on this run and your fix successfully prevented it from causing a problem.  

image
image

So I think this one is good to go!

**Comment by szabi-luxonis** [comment]
Nice.
I'm running it also on RPI, since I pushed the fix, I will check tomorrow morning, and if it's fine I will merge it.

**Comment by Luxonis-Brandon** [comment]
So @szabi-luxonis I'm seeing a new one on this PR: The neural output never occurs.  I'm wondering if something in sanitization is making it so all future results get blocked or similar.

I've started it on BW1097 (`python3 test.py`) and seen no network results 3 times in a row now.

**Comment by Luxonis-Brandon** [comment]
After hitting reset button on Myriad X it started working again.

**Comment by Luxonis-Brandon** [comment]
And I had run `python3 calibrate.py` prior to running `python3 test.py`.  So it could be some state-info stays after or something from calibrate.py which causes this problem.

**Comment by Luxonis-Brandon** [comment]
Haven’t seen that boot up issue again. And have been running this on BW1097 for 16+ hours now.

**Comment by Luxonis-Brandon** [comment]
So I meant to circle back that I tested this for a long time over the weekend.  My Raspberry Pi eventually hard-froze (mouse won't even move).  It seems to have run out of RAM, as evidenced by the HD LED being permanently on (see below):
image

So I tried going back to terminal only to get the system responsive (ctrl-alt-f6 IIRC), but it wouldn't budge and when I came back an hour or so later it had moved to terminal only, but wasn't usable.

So I had seen this exact behavior before on this same Pi when not doing anything with DepthAI, and it was immediately subsequent to TeamViewer being installed on this Pi... so the possibility exists that this has nothing to do with DepthAI.  

I've since removed teamviewer and I'm doing another long-term run.  It's ~36 hours in so far and fine.

**Pull request merged**
