### PR TITLE
Enable full FOV output from RGB camera

### PR DESCRIPTION
**Pull request by VanDavv**
With this PR, the preview from the RGB camera is adjusted to meet the full FOV aspect ratio

image

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Yes this is a lot nicer!  

image

So a quick question - the 1920x1080 (I presume that's the sensor config) is cropped out of the aspect ratio of the full image sensor, is that right?

**Comment by Luxonis-Brandon** [comment]
But it looks like the spatial location calculator is being used wrong.  Look at the location of the TV monitor in the background.  

I think the wrong locations are being used between depth and RGB.

**Comment by Luxonis-Brandon** [comment]
Here's a video showing it:

https://photos.app.goo.gl/RyohNDddfpEx6MF59

**Comment by VanDavv** [comment]
Yes, I saw that too, and I think that's due to the lack of RGB-Depth alignment. Started to work on it [here](https://github.com/luxonis/depthai/tree/depth_rgb_alignment) but had come issues

**Comment by Luxonis-Brandon** [comment]
So I think it's different than RGB depth alignment.  As w/out this PR the distances seem correct.

**Comment by Luxonis-Brandon** [comment]
Here's a video of what's in `main` for example:
https://photos.app.goo.gl/nayGAPHxqQWvYzU56

**Comment by VanDavv** [comment]
Full FOV preview was enabled in #433 due to performance requirements

**Pull request closed without merging**
