### PR TITLE
Remove deprecated stream from help

### PR DESCRIPTION
**Pull request by pamolloy**
Add all stream choices to help for -s
Remove newlines that were not rendered

### CODE REVIEW

**Comment by pamolloy** [comment]
Before:
```
  -s STREAMS [STREAMS ...], --streams STREAMS [STREAMS ...]
                        Define which streams to enable Format: stream_name or
                        stream_name,max_fps Example: -s metaout previewout Example: -s
                        metaout previewout,10 depth_sipp,10

```

After:
```
  -s {metaout,previewout,jpegout,left,right,depth,disparity,disparity_color,meta_d2h,object_tracker,rectified_left,rectified_right,color} [{metaout,previewout,jpegout,left,right,depth,disparity,disparity_color,meta_d2h,object_tracker,rectified_left,rectified_right,color} ...], --streams {metaout,previewout,jpegout,left,right,depth,disparity,disparity_color,meta_d2h,object_tracker,rectified_left,rectified_right,color} [{metaout,previewout,jpegout,left,right,depth,disparity,disparity_color,meta_d2h,object_tracker,rectified_left,rectified_right,color} ...]
                        Define which streams to enable as a space delimited list (e.g. "-s
                        metaout previewout"). Optionally, append the FPS with a comma to
                        each stream name (e.g. "-s metaout previewout,10").
```

**Comment by pamolloy** [comment]
I tried the `metavar` suggestions in https://stackoverflow.com/questions/9366369, but they did not appear to render as described. It probably isn't worth the time to implement a custom `HelpFormatter`.

**Review by Luxonis-Brandon — APPROVED** [review]
Looks good to me, even though a bit long, at least it is all there.

**Review by VanDavv — APPROVED** [review]
I think it's good to go, having a list of all available streams may be useful for some of the users

**Pull request merged**
